### ISSUE TITLE
yaml file conversion 

### ISSUE THREAD

**Issue by ayush0111124** [tvganesh/yorkr#5]
How to resolve yaml to rdata file conversion error 

Error in if (d[2] == 6) { : argument is of length zero

Please suggest, thanks

**Comment by bmp22** [comment]
I get the same problem, but only with some file conversions- certainly the more recent ones in  general.

```
> convertYaml2RDataframe("1144530.yaml","./odiData","./odiRData")
[1] "./odiData/1144530.yaml"
[1] "first loop"
Error in if (d[2] == 6) { : argument is of length zero
```

**Comment by tvganesh** [comment]
@ayush, @bmp 
                  I don't have time to debug this. I would suggest trying to debug the issue or excluding files that fail conversion. WIll try to get to it later. You could also try yorkpy. That has been done recently and should not have problems

Regards
Ganesh

**Comment by bmp22** [comment]
Of course! I hope you get time, it's a useful package! I'll see if I have time myself to find the problem...

**Comment by tvganesh** [comment]
@bmp - Cool. I it will be a different type of extra. You may find the equivalent Python code in yorkpy. You could check. 

Regards
Ganesh

**Comment by bmp22** [comment]
I think I found the problem- or at least a problem!

The order of output produced by cricsheet has changed.

For example, for 1144530.yaml (which does not convert) the first over has: 
```
- 1st innings:
    team: New Zealand
    deliveries:
    - 0.1:
        non_striker: HM Nicholls
        bowler: CR Woakes
        runs:
          extras: 1
          total: 1
          batsman: 0
        extras:
          wides: 1
        batsman: MJ Guptill
```
whereas for 913653.yaml (a file successfully converted!)
 ```
1st innings:
      team: Pakistan
      deliveries:
        - 0.1:
            batsman: Azhar Ali
            bowler: CR Woakes
            non_striker: Sharjeel Khan
            runs:
              batsman: 0
              extras: 0
              total: 0
        - 
```
In convertYaml2RDataframe.R there is a line 
`idx = which(names(b) == "1st 0.1.batsman")`
which I think picks out the first thing we are interested in. If I change this to 
`idx = which(names(b) == "1st 0.1.non-striker")`
then the conversion seems to make progress for the more recent match.

I'd hazard a guess that replacing with `idx=2` might work throughout, but I haven't checked this thoroughly yet.

Hope that's helpful!
